import { z } from 'zod';

export type Gender = 'MALE' | 'FEMALE' | 'OTHER' | 'UNKNOWN';

export interface Patient {
  id: string;
  mrn: string; // System-generated, read-only
  firstName: string;
  lastName: string;
  dateOfBirth: string; // ISO string
  gender: Gender;
  phone?: string;
  email?: string;
  createdAt: string;
  updatedAt: string;
  orders?: any[]; // Using any[] to prevent circular dependency issues with order.types.ts for now
}

// MRN is NOT included — it is auto-generated by the backend
export const patientFormSchema = z.object({
  firstName: z.string().min(1, 'First name is required'),
  lastName: z.string().min(1, 'Last name is required'),
  dateOfBirth: z.string().min(1, 'Date of Birth is required'),
  gender: z.enum(['MALE', 'FEMALE', 'OTHER', 'UNKNOWN']),
  phone: z.string().optional(),
  email: z.string().email('Invalid email address').optional().or(z.literal('')),
  forceCreate: z.boolean().optional(),
});

export type PatientFormData = z.infer<typeof patientFormSchema>;
