import { IsArray, IsNotEmpty, IsOptional, IsString, ValidateNested, IsNumber } from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class CreateOrderItemDto {
  @ApiProperty({ example: 'uuid-of-test', description: 'The ID of the test from the catalogue' })
  @IsString()
  @IsNotEmpty()
  testId: string;
}

export class CreateTestOrderDto {
  @ApiPropertyOptional({ example: 'ORD-2026-90812', description: 'Unique order number (generated by backend if omitted)' })
  @IsString()
  @IsOptional()
  orderNumber?: string;

  @ApiProperty({ example: 'uuid-of-patient', description: 'The ID of the patient' })
  @IsString()
  @IsNotEmpty()
  patientId: string;

  @ApiPropertyOptional({ example: 'uuid-of-doctor', description: 'The ID of the referring doctor (User)' })
  @IsString()
  @IsOptional()
  referringDoctorId?: string;

  @ApiPropertyOptional({ example: 'uuid-of-referral-request', description: 'The ID of the referral request (if applicable)' })
  @IsString()
  @IsOptional()
  referralRequestId?: string;

  @ApiProperty({ type: [CreateOrderItemDto], description: 'List of tests being ordered' })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CreateOrderItemDto)
  items: CreateOrderItemDto[];
}
